SREP-2215: Summarize results
openshift/operator-curator pull request #3
Opened 2019-10-08 19:49 UTC by clcollins

This PR addresses SREP-2215:

At the end of the operator-curator job execution, generate a summary of the reasons to reject/approve operators.

-  Output a summary at the job execution with a list of the reasons for each operator to be rejected by curation
-  List all possible reasons, not just the first one that triggered rejection
-  Display it in the Jenkins job output

*** 

Logging during run increased to allow investigation when necessary.
Summary is printed at end of run.
Summary printed to stdout; will be visible in Jenkins log
Overall failures aggregated for each operator.

Additional flags added for local development:
-  --cache; skips downloading package...uses local cache
-  --skip-push; skips pushing validated packages to Quay.io

Example of summary at end of run:

```
Validation Summary
------------------
[FAIL] community-operators/cert-utils-operator version 0.0.1
    [PASS] should not require security context constraints
    [PASS] bundle.yaml should be present
    [PASS] should not support multi-namespace install mode
    [FAIL] should not require cluster permissions

[FAIL] community-operators/cert-utils-operator version 0.0.3
    [FAIL] bundle.yaml should be present

[PASS] community-operators/atlasmap-operator version 0.0.1
    [PASS] should not require security context constraints
    [PASS] bundle.yaml should be present
    [PASS] should not support multi-namespace install mode
    [PASS] should not require cluster permissions
```

2019-10-08 19:50 UTC, clcollins commented
/cc @jewzaam @rogbas

2019-10-08 20:43 UTC, jewzaam requested changes

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +        tests["is whitelisted"] = True
```suggestion
        tests["is in allowed list"] = True
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +        tests["should not be blacklisted"] = False
```suggestion
        tests["is in denied list"] = False
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +            tests["bundle.yaml should be present"] = True
```suggestion
            tests["bundle.yaml must be present"] = True
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +            tests["bundle.yaml should be present"] = False
```suggestion
            tests["bundle.yaml must be present"] = False
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +            tests["should not require cluster permissions"] = True
```suggestion
            cpKey = "CSV must not include clusterPermissions"
            tests[cpKey] = True
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +                tests["should not require cluster permissions"] = False
```suggestion
                tests[cpKey] = False
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +            tests["should not require security context constraints"] = True
```suggestion
            sccKey = "CSV must not grant SecurityContextConstraints permissions"
            tests[sccKey] = True
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +                            tests["should not require security context constraints"] = False
```suggestion
                            tests[sccKey] = False
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +            tests["should not support multi-namespace install mode"] = True
```suggestion
            multiNsKey = "CSV must not require MultiNamespace installMode"
            tests[multiNsKey] = True
```

2019-10-08 20:43 UTC, jewzaam commented on curator.py
> +                    tests["should not support multi-namespace install mode"] = False
```suggestion
                    tests[multiNsKey] = False
```

2019-10-09 12:49 UTC, clcollins commented
@jewzaam Everything still works fine after incorporating your suggestions.

2019-10-09 14:12 UTC, jewzaam approved these changes

2019-10-09 14:13 UTC, jewzaam commented
/lgtm
/approve

2019-10-09 14:43 UTC, merged